theme: jekyll-theme-minimal
plugins:
  - jekyll-relative-links
relative-links:
  enabled: true
  collections: true
include:
  - README.md

title: C++ Data Structures
description: Notes and implementations on data structures in C++
